### ISSUE TITLE
Doesn't work over tramp

### ISSUE THREAD

**Issue by dkogan** [caldwell/commit-patch#11]
Hi. This worked over TRAMP. Then it was broken by this:

https://github.com/caldwell/commit-patch/commit/3d989938836498e7c263751a9fc1cea4a71335dc

Supposedly it's required for ELPA or something.

**Comment by caldwell** [comment]
Thanks, Dima. This would have also broken the Debian package had I released it.

The sad part is the MELPA talks came to a standstill (they refuse to pull from a non-master branch and I refuse to commit generated code to the master branch), so the code that broke TRAMP isn't actually useful yet.

This also makes me realize a MELPA/ELPA installed commit-patch wouldn't work over TRAMP (since emacs would have no idea where the executable exists on the other side).
